name: Terraform CI (fmt/validate/security)

on:
  pull_request:
  workflow_dispatch:

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Cambia esta ruta si tu terraform est√° en otra carpeta
      - name: Terraform fmt (check)
        run: |
          cd "DEVSECOPS-azure-sql"
          terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: |
          cd "DEVSECOPS-azure-sql"
          terraform init -backend=false

      - name: Terraform validate
        run: |
          cd "DEVSECOPS-azure-sql"
          terraform validate

      - name: Checkov (IaC security scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: DEVSECOPS-azure-sql
          quiet: true
          soft_fail: false
